import {Link,useParams} from 'react-router-dom';
import {useQuery} from '@tanstack/react-query';
import {getInternalAssessment} from '../lib/internal.functions';
import {emptyAssessment,type AssessmentData} from '../types';
import {maturityLevel,scoreAssessment} from '../scoring';
import ScoreGauge from '../components/ScoreGauge';
import DomainBars from '../components/DomainBars';
import ImpactChart from '../components/ImpactChart';
import SeverityBadge from '../components/SeverityBadge';
import logo from '../assets/logo-concierge.jpg';
import {AlertTriangle,ArrowLeft,BarChart3,Building2,Database,FileText,KeyRound,MonitorSmartphone,Server,ShieldCheck,Target,Wifi,Info} from 'lucide-react';

const money=(n:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n);
const usageLabel={light:'Leve',medium:'Médio',high:'Intenso'} as const;

export default function InternalResults(){
 const {id}=useParams();
 const {data,isLoading}=useQuery({queryKey:['internal-assessment',id],queryFn:()=>getInternalAssessment({data:{id:id!}}),enabled:!!id});
 if(isLoading)return <main className="min-h-screen bg-slate-950 p-8 text-slate-200">Carregando assessment…</main>;
 if(!data?.found)return <main className="min-h-screen bg-slate-950 p-8 text-slate-200">Assessment não encontrado.</main>;
 const s={id:data.assessment.id,createdAt:data.assessment.created_at,data:{...emptyAssessment,...(JSON.parse(data.answersJson) as Partial<AssessmentData>)}};
 const r=scoreAssessment(s.data);
 const domains=[
   {label:'Rede e Perímetro',value:r.scores.network,coverage:r.domainCoverage.network,confidence:r.domainConfidence.network,icon:<Server size={17} className="text-cyan-400"/>},
   {label:'Endpoints',value:r.scores.endpoint,coverage:r.domainCoverage.endpoint,confidence:r.domainConfidence.endpoint,icon:<MonitorSmartphone size={17} className="text-cyan-400"/>},
   {label:'Backup e Continuidade',value:r.scores.backup,coverage:r.domainCoverage.backup,confidence:r.domainConfidence.backup,icon:<Database size={17} className="text-cyan-400"/>},
   {label:'Identidade e Acesso',value:r.scores.identity,coverage:r.domainCoverage.identity,confidence:r.domainConfidence.identity,icon:<KeyRound size={17} className="text-cyan-400"/>}
 ];
 const severityCount={Alta:r.findings.filter(f=>f.severity==='Alta').length,Média:r.findings.filter(f=>f.severity==='Média').length,Baixa:r.findings.filter(f=>f.severity==='Baixa').length};
 const knownScore = r.overall!==null;
 return <main className="min-h-screen bg-dashboard-animate bg-grid-tech px-4 py-8 md:py-10"><div className="mx-auto max-w-7xl">
  <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><Link to="/interno" className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-white"><ArrowLeft size={16}/>Voltar aos assessments</Link><div className="flex items-center gap-3"><img src={logo} className="h-9 rounded-md"/><div className="hidden text-right text-xs text-slate-500 sm:block">Concierge Security Assessment<br/>Prévia interna</div></div></div>

  <section className="glass-card overflow-hidden p-6 md:p-8"><div className="grid gap-8 lg:grid-cols-[1.3fr_.7fr] lg:items-center"><div><div className="text-xs font-bold uppercase tracking-[.22em] text-teal-400">Security Assessment · Uso interno</div><h1 className="mt-3 text-4xl font-extrabold tracking-tight md:text-5xl">{s.data.companyName||'Empresa não informada'}</h1><p className="mt-3 max-w-3xl text-slate-400">Leitura executiva e técnica baseada nas respostas fornecidas. O score representa maturidade relativa dos controles avaliados, não probabilidade absoluta de ataque.</p><div className="mt-6 flex flex-wrap gap-2 text-sm"><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5">{s.data.sector||'Setor não informado'}</span><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5">{s.data.users||'—'} usuários</span><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5">{s.data.sites||1} unidade(s)</span><span className="rounded-full border border-slate-700 bg-slate-950/40 px-3 py-1.5">Dados respondidos: {r.completeness}%</span></div></div><div className="flex justify-center"><ScoreGauge value={r.overall}/></div></div></section>

  <section className="mt-5 grid gap-5 lg:grid-cols-3">
   <div className="glass-card p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Postura geral</div><div className="mt-2 text-3xl font-bold text-white">{r.overall??'—'}<span className="text-base font-semibold text-slate-600">/100</span></div></div><BarChart3 className="text-teal-400"/></div><div className="mt-3 text-sm text-slate-300">{knownScore?r.level:'Dados insuficientes'}</div><div className="mt-4 h-2 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-cyan-500 to-teal-400" style={{width:`${r.overall??0}%`}}/></div></div>
   <div className="glass-card p-6"><div className="flex items-center justify-between"><div className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Prioridade identificada</div><Target className="text-amber-400"/></div><div className="mt-3 text-2xl font-bold text-white">{r.priorityLabel}</div><p className="mt-2 text-sm text-slate-400">Prioridade calculada pelo gap de controles combinado com contexto operacional, exposição e criticidade informada.</p></div>
   <div className="glass-card p-6"><div className="flex items-center justify-between"><div className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Qualidade das respostas</div><ShieldCheck className="text-cyan-400"/></div><div className="mt-3 text-3xl font-bold text-white">{r.completeness}%</div><p className="mt-2 text-sm text-slate-400">Quanto maior a cobertura das respostas, mais contextualizado fica o diagnóstico.</p></div>
  </section>

  <section className="mt-5 grid gap-5 lg:grid-cols-[1.1fr_.9fr]">
   <div className="glass-card p-6 md:p-7"><div className="mb-6 flex items-center justify-between"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Visão comparativa</div><h2 className="mt-1 text-2xl font-bold">Maturidade por domínio</h2></div><Wifi className="text-slate-600"/></div><DomainBars items={domains}/></div>
   <div className="glass-card p-6 md:p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Distribuição dos achados</div><h2 className="mt-1 text-2xl font-bold">Onde está a atenção</h2><div className="mt-7 grid grid-cols-3 gap-3">{(['Alta','Média','Baixa'] as const).map(k=><div key={k} className="rounded-xl border border-slate-800 bg-slate-950/35 p-4 text-center"><div className={`text-3xl font-extrabold ${k==='Alta'?'text-rose-300':k==='Média'?'text-amber-300':'text-emerald-300'}`}>{severityCount[k]}</div><div className="mt-1 text-xs uppercase tracking-wide text-slate-500">{k}</div></div>)}</div><div className="mt-6 rounded-xl border border-slate-800 bg-slate-950/30 p-4"><div className="text-sm font-semibold text-slate-200">Leitura recomendada</div><p className="mt-2 text-sm leading-relaxed text-slate-400">Comece pelos achados de severidade alta no domínio prioritário. O resultado orienta a conversa, mas não substitui validação técnica.</p></div></div>
  </section>

  <section className="mt-9"><div className="mb-4 flex items-end justify-between gap-4"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Diagnóstico contextual</div><h2 className="mt-1 text-2xl font-bold">O que merece atenção</h2></div><div className="text-sm text-slate-500">{r.findings.length} achado(s)</div></div><div className="grid gap-4 lg:grid-cols-2">{r.findings.length?r.findings.map(f=><article key={`${f.domain}-${f.title}`} className="glass-card p-6"><div className="flex items-start justify-between gap-4"><div className="flex items-center gap-2 text-sm font-semibold text-slate-400"><AlertTriangle size={17} className="text-amber-300"/>{f.domain}</div><SeverityBadge severity={f.severity}/></div><h3 className="mt-4 text-xl font-bold leading-snug text-white">{f.title}</h3><div className="mt-4 space-y-3 text-sm leading-relaxed"><div><div className="text-xs font-bold uppercase tracking-[.12em] text-slate-600">O que identificamos</div><p className="mt-1 text-slate-300">{f.situation}</p></div><div><div className="text-xs font-bold uppercase tracking-[.12em] text-slate-600">Possível consequência</div><p className="mt-1 text-slate-300">{f.consequence}</p></div><div className="rounded-lg border border-slate-800 bg-slate-950/35 p-3 text-slate-400"><b className="text-slate-300">Ponto técnico avaliado:</b> {f.technical}</div></div></article>):<div className="glass-card p-6 text-slate-400">Nenhum achado prioritário foi gerado com os dados informados.</div>}</div></section>

  <section className="mt-9 grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><div className="glass-card p-6 md:p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Cenário operacional SMB</div><h2 className="mt-1 text-2xl font-bold">Impacto ilustrativo de uma indisponibilidade</h2><div className="mt-5 text-3xl font-extrabold text-white">{money(r.impactRange[0])} <span className="text-base font-medium text-slate-500">a</span> {money(r.impactRange[1])}</div><p className="mt-3 text-sm leading-relaxed text-slate-400">Faixa de referência construída com o porte informado, tempo tolerável de parada e custos operacionais parametrizados para SMB. Não representa previsão de perda.</p><div className="mt-5 rounded-xl border border-slate-800 bg-slate-950/35 p-4 text-sm text-slate-400"><div><b className="text-slate-200">Pessoas consideradas:</b> {r.impactAssumptions.people}</div><div className="mt-1"><b className="text-slate-200">Horas de indisponibilidade:</b> {r.impactAssumptions.hours}h</div></div></div><div className="glass-card p-6 md:p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Composição da faixa</div><h2 className="mt-1 text-2xl font-bold">De onde vem a estimativa</h2><div className="mt-6"><ImpactChart components={r.impactComponents}/></div><div className="mt-5 flex gap-2 rounded-xl border border-cyan-900/40 bg-cyan-950/15 p-4 text-sm text-slate-400"><Info size={18} className="mt-0.5 shrink-0 text-cyan-400"/><span>Os parâmetros financeiros ficam centralizados na engine para revisão antes da publicação. O objetivo é manter valores compatíveis com a realidade de pequenas e médias empresas.</span></div></div></section>

  <section className="mt-9 grid gap-5 lg:grid-cols-2">
    <div className="glass-card p-6 md:p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Opportunity Engine · uso interno</div><h2 className="mt-1 text-2xl font-bold">Aderência comercial por frente</h2><p className="mt-2 text-sm text-slate-500">Este indicador não altera o score técnico. Ele ajuda o AM a escolher a próxima conversa.</p><div className="mt-5 space-y-4">{([['Endpoint / EDR',r.opportunityFit.endpoint,r.opportunityNotes.endpoint],['Backup',r.opportunityFit.backup,r.opportunityNotes.backup],['Firewall',r.opportunityFit.firewall,r.opportunityNotes.firewall],['Identidade',r.opportunityFit.identity,r.opportunityNotes.identity]] as const).map(([label,value,note])=><div key={label} className="rounded-xl border border-slate-800 bg-slate-950/30 p-4"><div className="flex items-center justify-between gap-4"><span className="font-semibold text-slate-200">{label}</span><span className="font-bold text-teal-300">{value}/100</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className="h-full rounded-full bg-teal-500" style={{width:`${value}%`}}/></div><p className="mt-2 text-xs leading-relaxed text-slate-500">{note}</p></div>)}</div></div>
    <div className="glass-card p-6 md:p-7"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Dependency Engine</div><h2 className="mt-1 text-2xl font-bold">Sequência recomendada</h2><p className="mt-2 text-sm text-slate-500">Pré-requisitos identificados antes ou durante uma evolução de segurança.</p><div className="mt-5 space-y-3">{r.dependencies.length?r.dependencies.map((d,i)=><div key={`${d.area}-${i}`} className="rounded-xl border border-slate-800 bg-slate-950/30 p-4"><div className="flex items-center gap-2"><span className="rounded-full border border-amber-800/50 bg-amber-950/20 px-2 py-0.5 text-2xs font-bold uppercase tracking-wide text-amber-300">{d.status}</span><span className="font-semibold text-slate-200">{d.area}</span></div><p className="mt-2 text-sm leading-relaxed text-slate-400">{d.message}</p></div>):<div className="rounded-xl border border-slate-800 bg-slate-950/30 p-4 text-sm text-slate-400">Nenhuma dependência relevante foi identificada com as respostas atuais.</div>}</div></div>
  </section>

  <section className="mt-9"><div className="mb-4"><div className="text-xs font-bold uppercase tracking-[.16em] text-teal-400">Uso interno</div><h2 className="mt-1 text-2xl font-bold">Dados para pré-dimensionamento</h2><p className="mt-1 text-sm text-slate-500">Informações capturadas sem transformar o formulário do cliente em um checklist técnico extenso.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
   <div className="glass-card p-5"><Building2 className="text-cyan-400" size={20}/><div className="mt-3 text-xs uppercase tracking-wide text-slate-600">Capacidade</div><div className="mt-2 space-y-1 text-sm"><div>Usuários <b className="float-right text-white">{s.data.users||'—'}</b></div><div>Endpoints <b className="float-right text-white">{s.data.endpointCount||s.data.devices||'—'}</b></div><div>Servidores <b className="float-right text-white">{s.data.servers||0}</b></div><div>Unidades <b className="float-right text-white">{s.data.sites||1}</b></div></div></div>
   <div className="glass-card p-5"><Server className="text-cyan-400" size={20}/><div className="mt-3 text-xs uppercase tracking-wide text-slate-600">Rede</div><div className="mt-2 space-y-1 text-sm"><div>Links <b className="float-right text-white">{s.data.internetLinkCount||1}</b></div><div>Banda total <b className="float-right text-white">{s.data.links[0]?.speedMbps||'—'} Mbps</b></div><div>Uso <b className="float-right text-white">{usageLabel[s.data.networkUsage]}</b></div><div>VLANs <b className="float-right text-white">{s.data.vlans||0}</b></div></div></div>
   <div className="glass-card p-5"><Wifi className="text-cyan-400" size={20}/><div className="mt-3 text-xs uppercase tracking-wide text-slate-600">Acessos</div><div className="mt-2 space-y-1 text-sm"><div>VPN remota <b className="float-right text-white">{s.data.vpnRemote||0}</b></div><div>VPN entre unidades <b className="float-right text-white">{s.data.vpnSite||0}</b></div><div>Firewall <b className="float-right max-w-[140px] truncate text-white">{s.data.firewallVendor||s.data.firewallLevel}</b></div></div></div>
   <div className="glass-card p-5"><Database className="text-cyan-400" size={20}/><div className="mt-3 text-xs uppercase tracking-wide text-slate-600">Continuidade</div><div className="mt-2 space-y-1 text-sm"><div>Volume backup <b className="float-right text-white">{s.data.backupVolumeGb?s.data.backupVolumeGb+' GB':'—'}</b></div><div>Parada tolerada <b className="float-right text-white">{s.data.maxDowntime==='unknown'?'—':s.data.maxDowntime}</b></div></div></div>
  </div></section>

  <section className="mt-9 grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div className="rounded-2xl border border-teal-900/60 bg-teal-950/20 p-6"><div className="flex gap-3"><ShieldCheck className="mt-1 shrink-0 text-teal-400"/><div><h2 className="font-bold text-white">Metodologia desta versão</h2><p className="mt-2 text-sm leading-relaxed text-slate-300">Os scores representam maturidade relativa dos controles informados. Respostas “não sei informar” reduzem a cobertura e entram com valor neutro, evitando que a ausência de informação gere uma nota artificialmente alta ou uma penalização automática. As faixas e pesos permanecem centralizados em <code className="text-teal-300">src/scoring.ts</code> para validação antes do uso em produção.</p></div></div></div><div className="flex gap-3"><Link to="/diagnostico" className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-4 py-3 text-sm font-semibold text-slate-300 hover:border-teal-500/40"><FileText size={17}/>Novo teste</Link></div></section>
 </div></main>
}
