/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConcluidoRouteImport } from './routes/concluido'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as AuthenticatedInternoIndexRouteImport } from './routes/_authenticated/interno.index'
import { Route as AuthenticatedInternoIdRouteImport } from './routes/_authenticated/interno.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcluidoRoute = ConcluidoRouteImport.update({
  id: '/concluido',
  path: '/concluido',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInternoIndexRoute =
  AuthenticatedInternoIndexRouteImport.update({
    id: '/interno/',
    path: '/interno/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInternoIdRoute = AuthenticatedInternoIdRouteImport.update({
  id: '/interno/$id',
  path: '/interno/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/concluido': typeof ConcluidoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultado': typeof ResultadoRoute
  '/interno/$id': typeof AuthenticatedInternoIdRoute
  '/interno/': typeof AuthenticatedInternoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/concluido': typeof ConcluidoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultado': typeof ResultadoRoute
  '/interno/$id': typeof AuthenticatedInternoIdRoute
  '/interno': typeof AuthenticatedInternoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assessment': typeof AssessmentRoute
  '/auth': typeof AuthRoute
  '/concluido': typeof ConcluidoRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/resultado': typeof ResultadoRoute
  '/_authenticated/interno/$id': typeof AuthenticatedInternoIdRoute
  '/_authenticated/interno/': typeof AuthenticatedInternoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assessment'
    | '/auth'
    | '/concluido'
    | '/diagnostico'
    | '/resultado'
    | '/interno/$id'
    | '/interno/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessment'
    | '/auth'
    | '/concluido'
    | '/diagnostico'
    | '/resultado'
    | '/interno/$id'
    | '/interno'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assessment'
    | '/auth'
    | '/concluido'
    | '/diagnostico'
    | '/resultado'
    | '/_authenticated/interno/$id'
    | '/_authenticated/interno/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssessmentRoute: typeof AssessmentRoute
  AuthRoute: typeof AuthRoute
  ConcluidoRoute: typeof ConcluidoRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  ResultadoRoute: typeof ResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concluido': {
      id: '/concluido'
      path: '/concluido'
      fullPath: '/concluido'
      preLoaderRoute: typeof ConcluidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/interno/': {
      id: '/_authenticated/interno/'
      path: '/interno'
      fullPath: '/interno/'
      preLoaderRoute: typeof AuthenticatedInternoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interno/$id': {
      id: '/_authenticated/interno/$id'
      path: '/interno/$id'
      fullPath: '/interno/$id'
      preLoaderRoute: typeof AuthenticatedInternoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedInternoIdRoute: typeof AuthenticatedInternoIdRoute
  AuthenticatedInternoIndexRoute: typeof AuthenticatedInternoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedInternoIdRoute: AuthenticatedInternoIdRoute,
  AuthenticatedInternoIndexRoute: AuthenticatedInternoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssessmentRoute: AssessmentRoute,
  AuthRoute: AuthRoute,
  ConcluidoRoute: ConcluidoRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  ResultadoRoute: ResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
